### ISSUE TITLE
Convert man pages to markdown in repo?

### ISSUE THREAD

**Issue by jakecraige** [liftoffcli/liftoff#241]
Almost all CLI tools I work with _do not_ have them and I'd prefer to not have to learn this language or require contributors to learn it.

Thoughts?

**Comment by marcelofabri** [comment]
:+1:

**Comment by gfontenot** [comment]
I looked for markdown to man page converters back when I started working on them, but I didn't find anything that worked well enough. I don't find `mdoc` to be _that_ bad of a format, but I'd be interested in alternatives if people have ideas.
