### ISSUE TITLE
dyld warnings when running liftoff

### ISSUE THREAD

**Issue by mseijas** [liftoffcli/liftoff#264]
Hey guys,

Just installed liftoff, but every time I run it (either in an empty directory, or one that has a current xcode project) I get the following error response:

`dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path`

Any ideas what this could be about?

Thanks!

**Comment by brandonroth** [comment]
I started getting the same error as soon as I upgraded from 1.5 to 1.6.

**Comment by marcelofabri** [comment]
That's probably what https://github.com/CocoaPods/Xcodeproj/pull/312 fixed. Could you guys tell the version of `xcodeproj` you're using (`gem list | grep xcodeproj` should show that)?

**Comment by brandonroth** [comment]
```$ gem list | grep xcodeproj                                                                                                                                                                        2.0.0-p0
xcodeproj (0.28.2, 0.26.3, 0.24.2, 0.24.1, 0.23.1, 0.23.0, 0.21.0, 0.20.2, 0.19.4, 0.17.0)```

**Comment by gfontenot** [comment]
We're on an old version of Xcodeproj and probably (definitely) need to update.

**Comment by marcelofabri** [comment]
I did update it on a PR, but it's been a while (https://github.com/thoughtbot/liftoff/pull/225/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478L4)

**Comment by AliSoftware** [comment]
I have the same warning and I have `xcodeproj 1.0.0-beta.2`:

```
$ gem list xcodeproj

*** LOCAL GEMS ***

xcodeproj (1.0.0.beta.2, 0.28.2, 0.26.3)
```
```
$ liftoff --version
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Version: 1.6.0
```

(My Xcode is installed in the expected path `/Applications/Xcode.app`)

**Comment by gfontenot** [comment]
I wonder if this is actually related to `xcproj` needing to be re-built?

**Comment by marcelofabri** [comment]
@AliSoftware even having `xcodeproj 1.0.0-beta.2`, liftoff's Gemfile is locking to an older version (https://github.com/thoughtbot/liftoff/blob/master/Gemfile#L4)
